version: "3.8"

services:
  shard-1:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5435:5432"
    networks:
      - todos_network
    volumes:
      - shard1_data:/var/lib/postgresql/data

  shard-2:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5436:5432"
    networks:
      - todos_network
    volumes:
      - shard2_data:/var/lib/postgresql/data

  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8008:8000"
    depends_on:
      - shard-1
      - shard-2
    environment:
      SHARD1_DB_URL: postgresql://postgres:password@shard-1:5432/todo_db
      SHARD2_DB_URL: postgresql://postgres:password@shard-2:5432/todo_db
    networks:
      - todos_network

networks:
  todos_network:

volumes:
  shard1_data:
  shard2_data:
