version: "3.8"

services:
  db-primary:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    networks:
      - todos_network

  db-replica:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: on-failure
    volumes:
      - replica_data:/var/lib/postgresql/data
    depends_on:
      - db-primary
    user: postgres
    command: >
      bash -c "
      sleep 5 &&
      rm -rf /var/lib/postgresql/data/* &&
      pg_basebackup -h db-primary -D /var/lib/postgresql/data -U postgres -P -Fp -Xs -R &&
      chmod 0700 /var/lib/postgresql/data &&
      postgres
      "
    networks:
      - todos_network

  app:
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8008:8000"
    depends_on:
      - db-primary
      - db-replica
    environment:
      PRIMARY_DB_URL: postgresql://postgres:password@db-primary:5432/todo_db
      REPLICA_DB_URL: postgresql://postgres:password@db-replica:5432/todo_db
    networks:
      - todos_network

networks:
  todos_network:

volumes:
  primary_data:
  replica_data:
