version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      ETCD_ENABLE_V2: "true"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
    ports:
      - "2379:2379"
    networks:
      - todos_network

  db-1:
    image: registry.opensource.zalan.do/acid/spilo-15:3.0-p1
    environment:
      SCOPE: todo-cluster
      ETCD_HOST: etcd:2379
      PGPASSWORD_SUPERUSER: password
      PGUSER_SUPERUSER: postgres
    volumes:
      - db1_data:/home/postgres/pgdata
    ports:
      - "5435:5432"
      - "8009:8008"
    networks:
      - todos_network

  db-2:
    image: registry.opensource.zalan.do/acid/spilo-15:3.0-p1
    environment:
      SCOPE: todo-cluster
      ETCD_HOST: etcd:2379
      PGPASSWORD_SUPERUSER: password
      PGUSER_SUPERUSER: postgres
    volumes:
      - db2_data:/home/postgres/pgdata
    ports:
      - "5436:5432"
      - "8010:8008"
    networks:
      - todos_network


  haproxy:
    image: haproxy:2.8
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    restart: on-failure
    ports:
      - "5000:5000"
      - "7000:7000"
    networks:
      - todos_network
    depends_on:
      - db-1
      - db-2
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5675:5672"
      - "15675:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - todos_network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - todos_network

  app:
    build: ./app
    volumes:
      - ./app:/app
    restart: on-failure
    ports:
      - "8008:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@haproxy:5000/postgres
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    networks:
      - todos_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      haproxy:
        condition: service_started
  
  logger:
    build: ./logger
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      MONGO_URL: mongodb://mongodb:27017
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - todos_network

networks:
  todos_network:

volumes:
  db1_data:
  db2_data:
