# разрешаем локальные подключения через Unix-сокет
local   all             postgres                                trust
# разрешаем локальные подключения TCP/IP
host    all             all             0.0.0.0/0               trust
# репликация
host    replication     postgres        0.0.0.0/0               trust
